bootstrap-styled/bootstrap-styled

package.json
=> perf(package.json): removed scope from name

package.json
=> fix(doc): updated documentation and styled.

src/theme/makeOriginal.js
=> fix(name): adding meta _name to makeOriginal

package.json, src/theme/tests/makeOriginal.test.js
=> test(fix): fix checksum total in test

src/index.js, src/tests/theme.test.js, src/theme/index.js, src/theme/tests/index.test.js, src/utils/tests/index.test.js
=> fix(exports): corrected mistake with makeTheme export

src/utils/index.js
=> fix(toMakeTheme): deep merge into a new object instead of theme

README.md, docs/introduction.md, package.json
=> fix(documentation): introduction was having incorrect badge

.travis.yml
=> fix(greenkeeper): fix greenkeeper executing sonar

package.json
=> fix(dependencies): Upgrade all dependencies

.travis.yml
=> ci(cache): remove caching of node_modules

README.md, docs/introduction.md
=> fix(documentation): added logo in intro and in readme

package.json
=> chore(dependencies): revert rollup-umd-scripts to latest public version

package.json
=> fix(dependencies): revert rollup-umd-scripts to latest public version

package.json
=> fix(dependencies): fix terser

LICENSE.md, README.md, docs/introduction.md, package.json
=> doc(url): fix url

docs/combiningThemes.md
=> fix(combiningThemes): fix import of createMakeTheme

package.json
added --copy-files to copy files in lib distributed directory
owners to license your work …
=> fix(babel): copy files in lib

src/tests/index.test.js
=> test(index): fix wrong import

docs/variables/spacing.md, src/theme/index.js
=> chore(docs): spacers

src/theme/index.js
=> fix(colors): updated colors from bs 4

src/theme/index.js, src/theme/tests/index.test.js
=> test(index): update checksum

package.json, src/tests/theme.test.js, src/theme/index.js, src/theme/tests/index.test.js
=> feat(utilities): added $utilities to theme

src/theme/index.js
=> fix(variables): added more variables for tooltip

src/theme/tests/index.test.js
=> chore(test): fix test

docs/advancedTheming.md, docs/breakpoints.md
change grammar in the advancedTheming.md and breakpoints.md files
owners to license your work …
=> docs(advancedtheming.md breakpoints.md): change grammar
